In [ ]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Yes, there is a difference in the data type of variables list_ and array_list.

#### list_ is a Python list of strings, while array_list is a numpy array of strings.

#### Here is the code to print the data types of both variables:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


###### As you can see, list_ has a data type of list, while array_list has a data type of numpy.ndarray.

### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in list_
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

#### Yes, there will be a difference in the data type of the elements present in both the variables.

#### The variable "list_" may contain elements of any data type, whereas after the conversion, all the elements in the variable "array_list" will be converted to integers, as we have specified the data type as "int".

#### To print the data types of each element in both variables, you can use the dtype attribute for the NumPy array and the type() function for the list. Here's an example:

In [4]:
import numpy as np

list_ = [1, 2.5, '3', True]
array_list = np.array(object=list_, dtype=int)

# print data types of elements in list_
for elem in list_:
    print(type(elem))

# print data types of elements in array_list
print(array_list.dtype)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
int32


### Consider the below code to answer further questions:
###### import numpy as np
###### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
###### num_array = np.array(object = num_list)
### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

##### To find the shape and size of the NumPy array "num_array", we can use the shape and size attributes respectively. Here's the code:

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# Find the shape of the array
print("Shape of the array:", num_array.shape)

# Find the size of the array
print("Size of the array:", num_array.size)

Shape of the array: (2, 3)
Size of the array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [7]:
import numpy as np
zero_array = np.zeros((3,3))

print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy as np
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
